name: Generate Contributions profile

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - name: checkout dev
        uses: actions/checkout@v2
        with:
          ref: dev
      - uses: yoshi389111/github-profile-3d-contrib@0.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name "Nhan Vo"
          git config user.email "tinhnhanvh@gmail.com"
          git add -A .
          git commit -m "profile generated"
          git push
